apiVersion : v1 
kind: Service
metadata:
  name: docker-assignment-service
spec:
  type: NodePort
  selector:
    app: docker-assignment
  ports:
  - port: 8005
    targetPort: 8005
    nodePort: 30002